# Generated by Django 2.2.3 on 2019-09-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_of_nss', '0008_activity_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='slug',
        ),
    ]
