# Generated by Django 2.2.3 on 2019-09-26 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity_of_nss', '0010_auto_20190926_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time_of_activity',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
