# Generated by Django 2.2.3 on 2019-08-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190831_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junior_student',
            name='Status',
        ),
    ]
