# Generated by Django 2.2.3 on 2019-09-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_junior_student_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='junior_student',
            options={'default_permissions': 'view'},
        ),
    ]
