# Generated by Django 2.2.3 on 2019-09-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junior_student',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='junior_student',
            name='Sex',
        ),
        migrations.RemoveField(
            model_name='junior_student',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='senior_student',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='senior_student',
            name='Sex',
        ),
        migrations.RemoveField(
            model_name='senior_student',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='senior_student',
            name='Username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='branch',
        ),
        migrations.DeleteModel(
            name='gender',
        ),
        migrations.DeleteModel(
            name='junior_student',
        ),
        migrations.DeleteModel(
            name='senior_student',
        ),
        migrations.DeleteModel(
            name='status_of_student',
        ),
    ]
