# Generated by Django 2.2.3 on 2019-09-07 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nss_team_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of nss team memner', max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('achievement', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='nss_team_member_pics')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Status')),
                ('sex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Gender')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Branch')),
            ],
        ),
    ]
