# Generated by Django 2.2.3 on 2019-09-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190907_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nss_team_member',
            name='batch',
        ),
    ]
