# Generated by Django 2.2.3 on 2019-09-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_nss_team_member_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='nss_team_member',
            name='batch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
