# Generated by Django 2.2.3 on 2019-09-07 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_nss_team_member_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nss_team_member',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Batch'),
        ),
    ]
