# Generated by Django 2.2.3 on 2019-09-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190907_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nss_team_member',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Branch'),
        ),
        migrations.AlterField(
            model_name='nss_team_member',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Status'),
        ),
    ]
